### ISSUE TITLE
Explain what is the difference between counts and number of successes

### ISSUE THREAD

**Issue by opetchey** [opetchey/BIO144#32]
This might seem obvious to us, but came up recently. The confusion / uncertainty can be created at least when one describes how binary data can be coded, with "count" of number of successes in one column. So I think its worth reinforcing with students:

Count data: theoretically no upper limit on number of times an "event" (e.g., number of birds observed in a forest plot), not possible to express as a proportion.

Binomial data: upper limit on number of times and "event" is observed (e.g., number of deaths cannot be greater than number of living individuals), possible to express as proportion.

**Comment by stefaniemuff** [comment]
Thanks, I added a slide to lecture 10 (in week 11), just after the "wrong" analysis. I think it should be clear now.
