### ISSUE TITLE
"Significance" question in week 1

### ISSUE THREAD

**Issue by stefaniemuff** [opetchey/BIO144#38]
Hi Owen, I opened an issue, really nice feature:-)

I just spotted that there is a question in "Significance" in the graded assessment of week 1. Would it be more approriate to move it to week 9, where we discuss this topic?

In the option
"Statistical significance is often said to be when something is unexpected, given our expectation about what would happen by chance alone"
I think it is better to replace "by chance alone" by "under the null hypothesis".

**Comment by opetchey** [comment]
Quite possibly.
Though its probably never too early to have them realise the difference.

**Comment by opetchey** [comment]
moved
