### ISSUE TITLE
Lecture 8, slide 11-12

### ISSUE THREAD

**Issue by opetchey** [opetchey/BIO144#40]
Nice to put the quadratic lm in, because it shows that although the nonlinearity is well dealt with, the scale-location plot still shows an increase. This is indicating that in the real data the variance is increasing with the mean (fitted value), while the linear model with identity link is assuming variance constant and independent of the mean (fitted value). I think its worth mentioning in slide 12 this as one of the problems. This would link well with content on slide 13 about the variance of the poisson increasing as the mean increases.

On slide 22, first bullet, I suggest pointing out the big difference in the diagnostic plots is in the scale-location plot, which no longer shows an increasing relationship. This is the big effect of using a glm in this case.

Second bullet on slide 22... a glm is still linear regression :)

**Comment by stefaniemuff** [comment]
Thanks for pointing this out, I added adjusted the slides accordingly.

In my world (and that of my stats colleagues), "linear regression" is just a special case of a glm;)
