### ISSUE TITLE
graded assessment 5

### ISSUE THREAD

**Issue by stefaniemuff** [opetchey/BIO144#41]
In GA 5 I have tried the questions and didn't get all correct:-)

- Q1: the t-test is not actually model. Maybe reformulating the question to "Which of these is **based on** a linear model?" would be more precise?

- Q2: I can't do a  generalised linear model with the lm function;) Generalized is all the stuff with link function etc, so in general this isn't correct, right?

- Q4: I was confused by the degrees of freedom question. The designs that is described there seems to be nested (hierarchical) instead of factorial. Unfortunately, I think we don't have time to cover nested designs, too. Did I misunderstand something here?

**Comment by opetchey** [comment]
Q1 & Q2 fixed.
Q4. What gives the impression this is a nested / hierarchical design / experiment?

**Comment by stefaniemuff** [comment]
Sorry I almost forgot to continue with Q4. When I read the question, I interpreted it as:

- there are two treatments (0 and 1)
- in treatment 0 there are five categories, ie.., drugs (drug 1, drug 2, ...., drug5)
- in treatment 1 there are six categories, i.e., supplements (supplement 1, ...,supplement 6)

So "drug" and "supplement" seemed nested in treatment, because patients under treatment 0 cannot get supplements, and vice versa. 

Only when reading the answer it got clear that you meant that "drug" and "treatment" are two factors, and each combination goes with each...

**Comment by opetchey** [comment]
Its "fully factorial" :)
You questioned the questioned, rather than accepted it!
Feel free to edit it to make it clear / unambiguous.

**Comment by stefaniemuff** [comment]
Sure, I read that, but my stubborn mind didn't get it. I'm probably spoilt by all the medical studies, where treatment is always a covariate.....
