### ISSUE TITLE
r-scripts

### ISSUE THREAD

**Issue by stefaniemuff** [opetchey/BIO144#42]
I just solved the algae ANOVA example as if I was a student. Of course, I'm supposed to be much faster then them. However, I noticed that I loose too much time with looking up the right dplyr and ggplot commands (looks I'm a seasoned R veteran, but I'm really happy;-)). I'd highly appreciate the solution scripts to be more efficient. Also it will help me to **not** show my different opinion on that to the students, haha.
Also I think that our TAs should have the scripts, so all of us will definitely give the very same advide to the students. I know that by far not all of the TAs have so far embraced the Hadleyverse;)

**Comment by opetchey** [comment]
Great!
Scripts that contain the solutions are on the repo.
I've mentioned this to the TAs also.
