### ISSUE TITLE
GA 5, question 2

### ISSUE THREAD

**Issue by stefaniemuff** [opetchey/BIO144#44]
Owen, could you please again check question 2 in GA5? There still seems to be something wrong with it, thanks.

**Comment by opetchey** [comment]
I looked at it and can't see anything wrong with it...

**Comment by stefaniemuff** [comment]
Hm, I think the right answers don't match with the explanation. Also, students won't know what a generalized linear model is at that stage. The explanation mentions that these can be fitted with lm (can they? sure, but the results won't be sensible). Or did you mean **general** linear models (i.e., multiple linear models)?
