### ISSUE TITLE
Check access to GSwR, Hector, and other books.

### ISSUE THREAD

**Issue by opetchey** [opetchey/BIO144#84]

**Comment by stefaniemuff** [comment]
I was just wondering if we still want to recommend the Hector book? I only use chapters 9.1-9.3 for the binary regression lecture. I'm fine with it when students get access to the ebook, but I don't think it's justified that they buy it.

**Comment by opetchey** [comment]
I just checked there is still access to the books via the library.
I will still use some content from Hector, so leave it in the list.
