### ISSUE TITLE
Fix broken link to lecture handout

### ISSUE THREAD

**Issue by opetchey** [opetchey/BIO144#90]
Broken link on this page on openedx:
https://mnf.openedx.uzh.ch/courses/course-v1:MNF+BIO144+FS2018/courseware/c98208d823834d6ab6d898394c348c6d/4bbcac8f14d3402aa3e37fc62ec450c6/?activate_block_id=block-v1%3AMNF%2BBIO144%2BFS2018%2Btype%40sequential%2Bblock%404bbcac8f14d3402aa3e37fc62ec450c6

Existing link is:
https://github.com/opetchey/BIO144/blob/master/2_content/Unit_7/lecture/Bio144_2017_lecture7.pdf

Required link:
https://github.com/opetchey/BIO144/blob/master/2_content/Unit_7/lecture/Bio144_lecture7.pdf

**Comment by opetchey** [comment]
@stefaniemuff I think I fixed this appropriately, but please check. Also check if other links to your lectures are working?

**Comment by opetchey** [comment]
I hope you don't mind me assigning you. Do the same for me when required :)

**Comment by stefaniemuff** [comment]
Sure - that's perfect. In fact I renamed all the lecture note pdfs without the year, as you found out. Thanks for pointing it out!
