### ISSUE TITLE
GA 9

### ISSUE THREAD

**Issue by stefaniemuff** [opetchey/BIO144#97]
Please check the last question of GA9. I'm not sure if any of the answers are right, strictly speaking:-)

**Comment by opetchey** [comment]
I suspect that why the question is "which best", rather than "which perfectly". But if you can suggest an enhancement?

**Comment by stefaniemuff** [comment]
It's more that I (honestly) don't fully understand the answer that is suposed to be correct, which is now
-it is the function used to transform the predictions of the model (linear predictor)

What this describes is the inverse link function, so e.g. the exp() in the poisson model, whereas the link function is the log (sorry for the subtlety).

Would this one work?
- it is the function used to transform the expected values of the response variable

**Comment by opetchey** [comment]
You're the expert on this I think... feel free to improve the question as you see fit.
